# Site settings
name: Justin Winslow
title: Justin Winslow | Software Engineer
description: ''
url: https://justinawinslow.github.io/
baseurl: ''
email: justinwinslow55@gmail.com
cover: https://justinawinslow.github.io/img/og.png
logo: https://justinawinslow.github.io/img/emojis/technologist.png
resume: https://justinawinslow.github.io/resume.pdf
social:
  - title: email
    url: mailto:justinwinslow55@gmail.com
  - title: facebook
    url: https://www.facebook.com/justin.winslow.963/
  - title: github
    url: https://github.com/justinawinslow
  - title: linkedin
    url: https://www.linkedin.com/in/justin-a-winslow/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
